language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    global:
        - TEST_COMMAND="composer test"

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: SYMFONY_VERSION=4.0.*
        - php: 7.2
          env: SYMFONY_VERSION=4.1.*
        - php: 7.2
          env: SYMFONY_VERSION=4.2.*
        - php: 7.2
          env: SYMFONY_VERSION=4.3.*
        - php: 7.2
          env: SYMFONY_VERSION=4.4.*

before_install:
    - travis_retry composer self-update

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
