name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-lowest-version:
    name: Build lowest version
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.5.8
        with:
          php-version: '7.2'
          coverage: xdebug
          extension-csv: mbstring

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: composer update --no-interaction --prefer-stable --prefer-lowest --prefer-dist

      - name: Run tests
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4']
        symfony_version: ['4.2.*', '4.3.*', '4.4.*', '5.0.*']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.5.8
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extension-csv: mbstring

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --prefer-dist
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony_version }}

      - name: Run tests
        run: make test
